export const characterSpecSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "name",
    "gender",
    "lineage_mode",
    "primary_species",
    "secondary_species",
    "species_ratio",
    "world_style",
    "role",
    "positioning",
    "personality_keywords",
    "visual_keywords",
    "colors",
    "body",
    "height",
    "features",
    "outfit",
    "signature_item",
    "background_story",
    "mission",
    "catchphrase",
    "scene",
    "must_keep",
    "avoid",
    "prompts",
    "setting_description",
  ],
  properties: {
    name: { type: "string" },
    gender: { type: "string", enum: ["male"] },
    lineage_mode: { enum: ["pure", "hybrid"] },
    primary_species: { type: "string" },
    secondary_species: { type: "array", items: { type: "string" } },
    species_ratio: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["species", "ratio"],
        properties: {
          species: { type: "string" },
          ratio: { type: "number" },
        },
      },
    },
    world_style: { type: "string" },
    role: { type: "string" },
    positioning: { type: "string" },
    personality_keywords: { type: "array", items: { type: "string" } },
    visual_keywords: { type: "array", items: { type: "string" } },
    colors: {
      type: "object",
      additionalProperties: false,
      required: ["primary", "secondary", "accent", "neutral", "shadow"],
      properties: {
        primary: { type: "string" },
        secondary: { type: "string" },
        accent: { type: "string" },
        neutral: { type: "string" },
        shadow: { type: "string" },
      },
    },
    body: { type: "string" },
    height: { type: "string" },
    features: {
      type: "object",
      additionalProperties: false,
      required: ["ears", "tail", "eyes", "fur", "special_marks"],
      properties: {
        ears: { type: "string" },
        tail: { type: "string" },
        eyes: { type: "string" },
        fur: { type: "string" },
        special_marks: { type: "string" },
      },
    },
    outfit: { type: "string" },
    signature_item: { type: "string" },
    background_story: { type: "string" },
    mission: { type: "string" },
    catchphrase: { type: "string" },
    scene: {
      type: "object",
      additionalProperties: false,
      required: ["location", "action", "composition", "camera", "lighting"],
      properties: {
        location: { type: "string" },
        action: { type: "string" },
        composition: { type: "string" },
        camera: { type: "string" },
        lighting: { type: "string" },
      },
    },
    must_keep: { type: "array", items: { type: "string" } },
    avoid: { type: "array", items: { type: "string" } },
    prompts: {
      type: "object",
      additionalProperties: false,
      required: ["complete_scene", "reference_sheet", "avatar"],
      properties: {
        complete_scene: { type: "string" },
        reference_sheet: { type: "string" },
        avatar: { type: "string" },
      },
    },
    setting_description: { type: "string" },
  },
};
